stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -project OSFramework.xcodeproj -scheme OSFramework | xcpretty
    - xcodebuild test -project OSFramework.xcodeproj -scheme OSFramework -destination 'platform=iOS Simulator,name=iPhone X,OS=11.4' | xcpretty -s
  tags:
    - xcode

lint:
  stage: build
  script:
    - swiftlint > swiftlint.log
    - CI_MERGE_REQUEST_ID=$(curl --request GET --header "Private-Token: $GITLAB_PERSONAL_API_PRIVATE_TOKEN" "https://gitlab.veladan.org/api/v4/projects/$CI_PROJECT_ID/repository/commits/$CI_COMMIT_SHA/merge_requests" --insecure | jq --raw-output ".[0].id")
    - curl --request POST --header "Private-Token: $GITLAB_PERSONAL_API_PRIVATE_TOKEN" -d @swiftlint.log https://gitlab.veladan.org/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_ID/notes --insecure
    - unlink swiftlint.log
  tags:
    - xcode
  only:
    - merge-requests

variables:
  GIT_SSL_NO_VERIFY: "1"
