stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -project OSFramework.xcodeproj -scheme OSFramework | xcpretty
    - xcodebuild test -project OSFramework.xcodeproj -scheme OSFramework -destination 'platform=iOS Simulator,name=iPhone X,OS=11.4' | xcpretty -s
  tags:
    - xcode
    
variables:
  GIT_SSL_NO_VERIFY: "1"
