language: swift # or objective-c
osx_image: xcode8.3
script:
  - xcodebuild -scheme OSFramework -project OSFramework.xcodeproj -configuration Debug -enableCodeCoverage YES build test
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'OSFramework'